Add h3
Lina-tre/CodingSchool pull request #1
Opened 2018-05-04 16:09 UTC by Lina-tre

2018-05-08 08:07 UTC, Afelua requested changes

2018-05-08 08:07 UTC, Afelua commented on index.html
> +	<title>Наш первый сайт</title>
Title стоит заменить на тот, что лучше подходит к макету

2018-05-08 08:07 UTC, Afelua commented on index.html
> +					<img src="">
Здесь ещё можно добавить тег а: иконки будут являться ссылками

2018-05-08 09:07 UTC, Lina-tre commented on index.html
> +	<title>Наш первый сайт</title>
done

2018-05-08 09:07 UTC, Lina-tre commented on index.html
> +					<img src="">
done

2018-05-12 09:36 UTC, Afelua approved these changes

2018-05-12 09:36 UTC, Afelua commented on style.css
> +header{
К тегам стили писать не надо, только к классам

2018-05-14 09:50 UTC, merged

2018-05-16 15:39 UTC, Lina-tre commented on style.css
> +header{
исправила