Task 5
Lina-tre/CodingSchool pull request #2
Opened 2018-05-16 14:18 UTC by Lina-tre

2018-05-16 22:19 UTC, Afelua requested changes

2018-05-16 22:19 UTC, Afelua commented on index.html
> +		<div class="div-header">
Для всех верхних элементов тоже нужно было расставить примерные отступы

2018-05-16 22:19 UTC, Afelua commented on style.css
> +.benefits{
Здесь центрирование всего блока лучше всего сделать так:
`width: 900px (посмотрите, сколько примерно должно быть по макету);
margin: 0 auto;`

Тогда можно будет убрать эти строки:
`margin-top: 0px;
padding-right: 90px;  
padding-left: 90px;`

и при больших расширениях все будет отрабатывать корректно.

2018-05-16 22:19 UTC, Afelua commented on style.css
> +.my-section{
см. комментарий про benefits, применить его для .my-section

2018-05-16 22:19 UTC, Afelua commented on style.css
> +	justify-content:
Такой код не сработает, если пишите свойство justify-content, то у него должно быть и значение. Для центрирование текста по центру стоит записать: `text-align: center;`

2018-05-16 22:19 UTC, Afelua commented on style.css
> +.my-section{
Либо, как вариант, можно еще записать     justify-content: center; - это альтернативные решения одного и того же

2018-05-16 22:19 UTC, Afelua commented on style.css
> +.my-section{
justify-content: center;  будет срабатывать только если применено display: flex;

2018-05-16 22:19 UTC, Afelua commented on index.html
> +		<section class="second-section">
Этот элемент полностью повторяет предыдущий, а, значит, у них должны быть одинаковые классы

2018-05-28 14:13 UTC, Lina-tre commented on index.html
> +		<div class="div-header">
+

2018-05-28 14:13 UTC, Lina-tre commented on style.css
> +.benefits{
+

2018-05-28 14:14 UTC, Lina-tre commented on style.css
> +.my-section{
done

2018-05-28 14:14 UTC, Lina-tre commented on style.css
> +	justify-content:
done

2018-05-28 14:14 UTC, Lina-tre commented on index.html
> +		<section class="second-section">
done

2018-05-28 21:21 UTC, Afelua commented on index.html
> +		<div class="div-header">
Все равно не вижу отступов до картинки слева и сверху и до меню сверху
<img width="1437" alt="screen shot 2018-05-29 at 00 21 23" src="https://user-images.githubusercontent.com/8777546/40629806-3ebb98e0-62d6-11e8-87d4-f8a9c13b68dc.png">

2018-05-28 21:23 UTC, Afelua commented on style.css
> +.benefits{
Все хорошо, только зеленый фон сбоку пропадает. Чтобы это поправить, стоит либо задать зеленый фон у main, либо создать еще один дополнительный элемент над benefits и залить зеленым цветом его.
<img width="1440" alt="screen shot 2018-05-29 at 00 22 45" src="https://user-images.githubusercontent.com/8777546/40629845-81f88d20-62d6-11e8-83fe-c976a4eb1a20.png">

2018-05-28 21:26 UTC, Afelua commented on style.css
> +.my-section{
Давайте поставим так:

.my-section {
    display: flex;
    width: 1093px;
    margin: 0 auto;
}

цвет фона задавать не будет, позиционируем по центру (margin: 0 auto;) и задаем точную ширину. Тогда все встанет корректно.

2018-05-28 21:28 UTC, Afelua requested changes
Потребуются небольшие правки

2018-06-05 11:48 UTC, Lina-tre commented on index.html
> +		<div class="div-header">
сорри, сделала

2018-06-05 11:52 UTC, Lina-tre commented on style.css
> +.benefits{
done

2018-06-05 11:55 UTC, Lina-tre commented on style.css
> +.my-section{
done

2018-06-05 18:25 UTC, Afelua approved these changes

2018-06-06 08:24 UTC, merged